#!/bin/bash

for f in *.dcf
  do
    compiler --opt $f
    done

for f in *.asm
  do
    nasm -f elf64 $f
    done

scp buildscript *.o *.out le05@silver.csail.mit.edu:
ssh le05@silver.csail.mit.edu "./buildscript"
