#!/bin/bash

for f in *.dcf
  do
    compiler --opt $f
    done

for f in *.asm
  do
    nasm -f elf64 $f
    done

scp buildscript *.o le05@silver.csail.mit.edu:final
ssh le05@silver.csail.mit.edu "cd final && ./buildscript"
